name: Podcast Generator
author: Arush
description: generates a pod cast feed
runs:
 using: Docker
 image: Dockerfile
branding: 
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: email
    required: True
    default: ${{ GITHUB_ACTOR }}@localhost
  name: 
    description: name
    required: True
    default: ${{ GITHUB_ACTOR }}  
